### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Gunter038**
Added one translation link. Yaz, maybe you should change your name on Crowdin to Celestia Labs, and add Celestia's Logo to your profile.

Then, on Crowdin, we would need you to create a project for the website, another one for the ressources (like Nader's video), and one project for the whitepapers. I think that you'll need to fulfill the form as you did before to get the free version.

### CODE REVIEW

**Comment by Ting2005** [comment]
cruel

**Comment by Gunter038** [comment]
I was think about something...The fact of modifying the name of the account might create an obsolete link...

**Comment by YazzyYaz** [comment]
@Gunter038 not sure I follow, why would we need to do this? 

The project link for the doc translation is here: https://crowdin.com/project/celestia-docs

We can just make one called celestia-org for the website. The PR adds my username btw, not the project link for translation.

**Comment by Gunter038** [comment]
@YazzyYaz, 

It would be cool to have one link to have access to all the projects. 

By the way, it looks more professional, and people wouldn't have to look for other translations. Have a look at eth : 
 
image

We would have a community space for translations and be able to add one link here : 

image

and here : 

image

By the way, we should have a call to discuss about docs, before I open a pull request to add the translations. What do you think? @Ting2005 and the Chinese community did a great job ! 

Then we should communicate on this with the rest of the community.

**Comment by Ting2005** [comment]
It is a question worth thinking about

**Pull request closed without merging**
