### PR TITLE
Added StakeTown contributions

### PR DESCRIPTION
**Pull request by mogoll92**
Added contributions from StakeTown

### CODE REVIEW

**Comment by jcstein** [comment]
gm @mogoll92 please resolve conflicts. thanks!

**Review by jcstein — CHANGES_REQUESTED** [review]
gm @mogoll92 please resolve conflicts. thanks!

**Comment by mogoll92** [comment]
> gm @mogoll92 please resolve conflicts. thanks!

done

**Comment by jcstein** [comment]
thanks! every time a new PR is merged, conflicts will arise and I will still not have write access to resolve. can you please modify this PR so I have write access to modify it? thanks! then I'll resolve issues.

**Comment by mogoll92** [comment]
> thanks! every time a new PR is merged, conflicts will arise and I will still not have write access to resolve. can you please modify this PR so I have write access to modify it? thanks! then I'll resolve issues.

updated PR

**Pull request merged**
