### PR TITLE
Update of Spanish-speaking community resources & Add Cumulo Contributions

### PR DESCRIPTION
**Pull request by santosdios**

### CODE REVIEW

**Review by jcstein — CHANGES_REQUESTED** [review]
gm 😄 @santosdios can you please resolve conflicts? thanks!

**Comment by santosdios** [comment]
I don't know what the hell I've done, I'm going to do the PR again.

**Comment by jcstein** [comment]
oh no it was me! i'm merging all of the PRs so one of the ones that i merged (or all of them) conflict with each other 😅

**Comment by jcstein** [comment]
did you also want to add back your contributions? 😄

**Comment by santosdios** [comment]
😄😄 I think we are both very busy this week ha ha, ... yes of course in a few hours I will do another PR, thanks!!

**Pull request closed without merging**
